language: cpp
compiler: gcc
os:
    - linux
    - osx

before_install:
    - MINICONDA_VERSION=latest
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
    - MINICONDA_PY=3
    - wget https://repo.anaconda.com/miniconda/Miniconda$MINICONDA_PY-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p "$HOME"/miniconda
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - hash -r 
    - conda config --set always_yes yes --set changeps1 no
    - conda install conda-build
    - conda config --add channels conda-forge
    - conda config --add channels demorest
    - conda config --add channels sevastien
    - conda info -a
    - export LANG=en_US.UTF-8
script:
    - conda build ./recipe -c demorest -c conda-forge
after_success:
    - conda activate base
    - export PKGFILE=$(conda build ./recipe -c demorest -c conda-forge --output)
    - conda install anaconda-client
    - anaconda -t $CONDA_UPLOAD_TOKEN upload -u sevastien --force $PKGFILE
